name: Create-Screenshot
on:
  release:
    types: [ created ]
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install pelican
      run: |
        python -m pip install --upgrade pip
        python -m pip install "pelican[markdown]"
    - name: Setup Node
      uses: actions/setup-node@v3
    - run: |
        mkdir dist
        npm install --global capture-website-cli
        pelican sample/content -s sample/settings.py -t .
        pelican --listen &
    - run: capture-website "http://127.0.0.1:8000" --dark-mode --output "dist/out.png"
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: dist/out.png
    - name: Checkout tyler-carr.com
      uses: actions/checkout@v2
      with: 
        repository: 'tcarwash/tyler-carr.com'
        path: 'tyler-carr.com'
    - run: |
        mkdir -p tyler-carr.com/content/images/ftp
        cp dist/out.png tyler-carr.com/content/images/ftp/out.png
    - name: create pull request on tyler-carr.com
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.pr_token }}
        path: 'tyler-carr.com'
        add-paths: 'tyler-carr.com/content/images/ftp/out.png'
        commit-message: 'blue-penguin-dark update $(git rev-parse --short HEAD)'
        delete-branch: True

